### ISSUE TITLE
Where is the settings?  Use to show in upper left.

### ISSUE THREAD

**Issue by molitar** [Mayriad/Mayriads-EH-Master-Script#2]

**Comment by Mayriad** [comment]
Nothing has changed, so something is wrong at your end. Can you see whether any of its features are active? [Is this script enabled in your Violentmonkey](https://forums.e-hentai.org/index.php?showtopic=237952&st=0&p=5670685&#entry5670685)? If you open your browser console, do you see any error messages?

**Comment by molitar** [comment]
Sorry I figured it out.  My bookmark has a filter in it and it only shows on the front page itself. It does not show when you filter. I had to click on front page.

**Comment by Mayriad** [comment]
Do you mean the button only shows on the front page and not on a search result page? That would be abnormal.

**Comment by molitar** [comment]
> 
> 
> Do you mean the button only shows on the front page and not on a search result page? That would be abnormal.

Yes if that is the case I'll try to reinstall it and see if that fixes it.

**Comment by Mayriad** [comment]
No further activity after 2 months. Closing issue.
