### ISSUE TITLE
I noticed the reader not fitting vertically...

### ISSUE THREAD

**Issue by alidan** [Mayriad/Mayriads-EH-Master-Script#8]
I use violent monkey and it seems that the script just stopped working. I noticed when one of the galleries didnt fit the image vertically. 

any idea if this is a me problem or if this is something else?

**Comment by Mayriad** [comment]
Yeah, I removed a bit too many `@grant`s to make `openuserjs.org`, where this script is hosted for download and auto-update, accept my update. A new update `v2.2.2` has been pushed to fix this issue, so you should be fine after updating again.
